### PR TITLE
a basic GitHub Actions config, run build/check on each new commit

### PR DESCRIPTION
**Pull request by dimpase**

### CODE REVIEW

**Comment by dimpase** [comment]
should we move this repo to https://github.com/sagemath ?

**Comment by jpflori** [comment]
> should we move this repo to https://github.com/sagemath ?

Sure, please do.

**Comment by dimpase** [comment]
I lack permissions on this repo to do so - you'd need to do it yourself, or elevate me to an admin or whatever it is called.

**Comment by jpflori** [comment]
Yes indeed, got a wrong Dima :/

**Comment by jpflori** [comment]
You should have received an invite now.

**Comment by dimpase** [comment]
I still haven't got admin. Having push access is still less than admin...

**Comment by jpflori** [comment]
I've transferred the repo to sagemath.
It did not seem I could give you more rights on my repo.

**Comment by dimpase** [comment]
GitHub gets more and more confusing, just as every "mature" project :-)

OK, this is good too. We'd need a new release (by the way, I checked that on macOS things work now, too)

**Pull request merged**
